### ISSUE TITLE
There's a issue here!

### ISSUE THREAD

**Issue by mprisciano** [nccgroup/umap#5]
When I execute as root this: python umap.py -P /dev/ttyUSB0 -h, it reports me this issue.  How can I fix it?

**Comment by mprisciano** [comment]
![screenshot from 2015-08-18 22 47 37](https://cloud.githubusercontent.com/assets/12964909/9339485/a2fbd916-45ea-11e5-9378-2efd216813cf.png)

**Comment by apdavis** [comment]
It appears you are not using Python 3.x, which is required to run umap. Please check your Python version and try running it again.

**Comment by mprisciano** [comment]
![screenshot from 2015-08-18 23 16 45](https://cloud.githubusercontent.com/assets/12964909/9340190/a66a7036-45ee-11e5-8cbf-b623bf3dec6a.png)

**Comment by mprisciano** [comment]
It was already the newest version :/

**Comment by lllama** [comment]
My guess is that you will have both versions installed. What version is displayed when you just run python on its own?

**Comment by lllama** [comment]
Your can also try  running the umap command with 'python3' instead of 'python' at the start.

**Comment by mprisciano** [comment]
I fixed it, anyway. Thank you!

**Comment by lllama** [comment]
I'm assuming that running under python 3 was the fix but let us know if that was not the case.
