### ISSUE TITLE
problem using umap with facedancer 21

### ISSUE THREAD

**Issue by dummys** [nccgroup/umap#7]
Hello, I get this problem using it:

-> $ sudo python3 umap.py -P /dev/ttyUSB1 -i                                                         1 ↵

---

---

| | | | '_ `_ \ / _` | '_ \
| |_| | | | | | | (_| | |_) |
 __,_|_| |_| |_|__,_| .__/
                      |_|  

The USB host assessment tool
Andy Davis, NCC Group 2013
Version: 1.03

Based on Facedancer by Travis Goodspeed
## For help type: umap.py -h

01:01:00 - Audio : Audio control : PR Protocol undefined
Traceback (most recent call last):
  File "umap.py", line 634, in <module>
    identify_classes(devtmp)
  File "umap.py", line 565, in identify_classes
    connect_as_audio (device_vid, device_pid, device_rev, 1)
  File "umap.py", line 366, in connect_as_audio
    fd = Facedancer(sp, verbose=ver1)
  File "/home/mofo/works/tools/usb/umap/Facedancer.py", line 13, in **init**
    self.reset()
  File "/home/mofo/works/tools/usb/umap/Facedancer.py", line 28, in reset
    c = self.readcmd()
  File "/home/mofo/works/tools/usb/umap/Facedancer.py", line 52, in readcmd
    app = b[0]
IndexError: index out of range

**Comment by apdavis** [comment]
What is the target USB host device and OS you are connected to?

**Comment by dummys** [comment]
Target is windows 7, my machine is archlinux facedancer21 latest goodfet web firmware

**Comment by dummys** [comment]
I change the facedancer21 and now seems to be ok. Another question with the mass storage device, I created a stick.img with dd if=/dev/sdb of=stick.img and running the umap with  -P /dev/ttyUSB1 -e 08:06:50 -v 1D0D -p 0213 and the windows machine hang adding the new device. Normally with this mode, are you able to see the file in the stick.img or not ?

**Comment by apdavis** [comment]
No because the facedancer hardware isn't really fast enough to properly emulate a mass storage device in general usage

**Comment by dummys** [comment]
Oh okay :D, because the windows machine is hangging very hard, no mouse/keyboard is working during the emulation.
